#!/usr/bin/env bash
# script to configure broken container to work with nginx at port 8080
# restart nginx as nginx user
wget -O do_fix https://raw.githubusercontent.com/amirakame/system_engineering-devops/tree-master/0x12-web_stack_debugging_2
chmod u+x do_fix
./do_fix
